# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

networks:
  demoapp:

services:
  demoappdb:
    container_name: demoappdb
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    networks:
      - demoapp
  api:
    container_name: demo-api
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - demoappdb
    environment:
      - DB_HOST=demoappdb
      - DB_NAME=DemoApp
      - DB_SA_PASSWORD=yourStrong(!)Password
    networks:
      - demoapp
